# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7abe2b37361488f6e07eb0094fd7feabc12e85f3948cdbbed76c756d732ec3574567bb2ff17ee4d5e310ad2c2c345ace531a5cb82ae255c59eefe5d743b5a7cb

test:
  secret_key_base: 576241e6d0d1caec605dddc49a7b55d7b382bdefd7ab8b9782b36717bcdfbb8c23af0598ea71b753485bd9d08687f6565c6f02fb3be542eb06d9787a1c522b70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
